### ISSUE TITLE
Unable to add default style to root element of editable

### ISSUE THREAD

**Issue by abhrabhattacharyya** [luigiinred/react-ckeditor-wrapper#11]
I'm using ckeditor as a compose e-mail editor tool. As per the requirement the font-family should be 'Verdana'. Now, I can change the style of the editor on browser by changing in the content.css but when I'm sending the html as a mail-body the default style doesn't get added. Only the selected styles from the toolbar gets added as inline style.
Is there a way to add inline style as default on the root element of the editable text-area?

**Comment by kaunio** [comment]
Hi Abhra Bhattacharyya,

This project only deals with the actual react wrapper of the ckeditor. The question you have is more related to the actual ckeditor itself. You will find better help if you address the main project directly (https://ckeditor.com/).

Good luck!
