### ISSUE TITLE
How to add plugins

### ISSUE THREAD

**Issue by anuragnagarkota** [luigiinred/react-ckeditor-wrapper#5]
Hi

First of all kudos and thanks for integrating the most popular wysiwyg editor with react.

Please guide to add plugins in it. I want to add mathjax in it (https://ckeditor.com/addon/mathjax).

Thanks in advance

**Comment by luigiinred** [comment]
Sorry I'm so unresponsive. 

If you want to add plugins, you can't use ckeditor from the cnd. 

You can download ckditor with mathjax installed here and include it in your project

[https://ckeditor.com/download](https://ckeditor.com/download) 

```html
     <script src="assets/ckeditor/ckeditor.js"></script>
```
